development:
  adapter: postgresql
  encoding: unicode
  database: store_manager
  pool: 5
  username: andela
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: store_manager_test
  pool: 5
  username: andela
  password:
  timeout: 5000

production:
  # <<: *default
  # database: db/production.sqlite3
